import {
  BillingInterval,
  SubscriptionPlanStatus,
} from "../../prisma/generated";
import { prisma } from "../config/db.config";

const mockPlans = [
  {
    id: 1,
    uid: "starter-free-plan",
    name: "Starter",
    price: "0",
    currency: "USD",
    description: "For new or testing users",
    status: SubscriptionPlanStatus.ACTIVE,
    gracePeriod: 8,
    tax: 0,
    discountForAnnually: 30,
    interval: BillingInterval.MONTHLY,
    features: {
      stores: 1,
      products: 100,
      analytics: false,
      custom_branding: true,
      priority_support: false,
      store_analytics: false,
      unlimited_products: false,
      hide_banner: false,
      api_access: false,
      custom_domain: false,
      ai_features: false,
      customer_emails: false,
      free_ssl: true,
      available_templates: 1,
      custom_templates: false,
      payment_gateways: 2,
      default_template: true,
      staff_accounts: 0,
      order_syncing_for_social_media_store: false,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 2,
    uid: "essentials-plan",
    name: "Essentials",
    price: "20",
    currency: "USD",
    description: "For early-stage sellers",
    status: SubscriptionPlanStatus.ACTIVE,
    gracePeriod: 8,
    tax: 10,
    discountForAnnually: 30,
    interval: BillingInterval.MONTHLY,
    features: {
      stores: 5,
      products: 200,
      analytics: true,
      custom_branding: true,
      priority_support: false,
      store_analytics: false,
      unlimited_products: false,
      hide_banner: false,
      api_access: false,
      custom_domain: true,
      ai_features: false,
      customer_emails: true,
      free_ssl: true,
      available_templates: 2,
      custom_templates: false,
      payment_gateways: 10,
      default_template: true,
      staff_accounts: 0,
      order_syncing_for_social_media_store: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 3,
    uid: "pro-plan",
    name: "Pro",
    price: "40",
    currency: "USD",
    description: "For consistent sellers and resellers",
    status: SubscriptionPlanStatus.ACTIVE,
    gracePeriod: 8,
    tax: 10,
    discountForAnnually: 30,
    interval: BillingInterval.MONTHLY,
    features: {
      stores: 20,
      products: 500,
      analytics: true,
      custom_branding: true,
      priority_support: false,
      store_analytics: true,
      unlimited_products: false,
      hide_banner: true,
      api_access: false,
      custom_domain: true,
      ai_features: true,
      customer_emails: true,
      free_ssl: true,
      available_templates: 10,
      custom_templates: true,
      payment_gateways: 25,
      default_template: false,
      staff_accounts: 0,
      order_syncing_for_social_media_store: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 4,
    uid: "business-plan",
    name: "Business",
    price: "80",
    currency: "USD",
    description: "For growing vendors and businesses",
    status: SubscriptionPlanStatus.ACTIVE,
    gracePeriod: 8,
    tax: 10,
    discountForAnnually: 30,
    interval: BillingInterval.MONTHLY,
    features: {
      stores: 100,
      products: 1000,
      analytics: true,
      custom_branding: true,
      priority_support: true,
      store_analytics: true,
      unlimited_products: true,
      hide_banner: true,
      api_access: true,
      custom_domain: true,
      ai_features: true,
      customer_emails: true,
      free_ssl: true,
      available_templates: 20,
      custom_templates: true,
      payment_gateways: 50,
      default_template: false,
      staff_accounts: 5,
      order_syncing_for_social_media_store: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    id: 5,
    uid: "empire-plan",
    name: "Empire",
    price: "150",
    currency: "USD",
    description: "For high-volume sellers and teams",
    status: SubscriptionPlanStatus.ACTIVE,
    gracePeriod: 8,
    tax: 10,
    discountForAnnually: 30,
    interval: BillingInterval.MONTHLY,
    features: {
      stores: 999999,
      products: null,
      analytics: true,
      custom_branding: true,
      priority_support: true,
      store_analytics: true,
      unlimited_products: true,
      hide_banner: true,
      api_access: true,
      custom_domain: true,
      ai_features: true,
      customer_emails: true,
      free_ssl: true,
      available_templates: 999,
      custom_templates: true,
      payment_gateways: 100,
      default_template: false,
      staff_accounts: 10,
      order_syncing_for_social_media_store: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function main() {
  for (const plan of mockPlans) {
    await prisma.subscriptionPlan.upsert({
      where: { uid: plan.uid },
      update: plan,
      create: plan,
    });
    console.log(`Plan ${plan.name} added/updated`);
  }

  console.log("All plans seeded successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
