name: 🚀 Deploy to server on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload & Run Remote Commands
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Install deps & build
        env:
          DATABASE_URL: "postgresql://build:build@localhost:5432/build_only"
        run: |
          npm ci
          npm run build

      - name: 📤 Upload project (excluding src/)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2022
          source: "app,public,scripts,prisma,package.json,prisma.config.ts"
          target: "core-platform/backend"
          overwrite: true

      - name: 🧠 Run post-deploy commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 2022
          script: |
            cd core-platform/backend
            npm i --omit=dev
            npm run migrate
            pm2 describe core-platform > /dev/null \
              && pm2 restart core-platform \
              || pm2 start app/index.js --name core-platform
            pm2 save
